services:
  dynamodb:
    container_name: "dynamodb"
    image: amazon/dynamodb-local:latest
    ports:
      - "127.0.0.1:8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb"]
    volumes:
      - "${DYNAMODB_VOLUME_DIR:-./volume}:/home/dynamodblocal/data"